et:
  languageCode: et
  contentDir: content/et
  title:  ' '
  params:
    description: 'SEO, kohalik SEO, Kodulehed, Veebipoed, Digiturundus, WooCommerce. Me teame täpselt, kuidas aidata väikeettevõtteid, sest me ise oleme üks neist.'
  menu:
    main:
      - name: SEO
        url: '/'
        weight: 10
      - name: Teenused
        url: '/et/seo/'
        weight: 20
      - name: Edulood
        url: '/et/edulood/'
        weight: 30        
      - name: Meist
        url: '/et/#about'
        weight: 40
      - name: Kontakt
        url: '/et/#contact'
        weight: 50
#ru:
#  languageCode: ru
#  contentDir: content/ru
#  title: 'SEO и Услуги интернет маркетинга'
#  params:
#    description: 'SEO, Местное SEO, Реклама в Google и Facebook, дизайн и разработка сайтов и магазинов, WooCommerce. Мы знаем, как помочь малому бизнесу, потому что сами такие.'
#  menu:  
#    main:
#      - name: 'O нас'
#        url: '/#about'
#        weight: 30
#      - name: 'SEO услуги'
#        url: 'seo/uslugi/'
#        weight: 10
#      - name: Блог
#        url: '/#posts'
#        weight: 20
#      - name: Контакт
#        url: '/#contact'
#        weight: 40
en:
  languageCode: en
  contentDir: content/en
  title: ' '
  params:
    description: 'SEO, Local SEO, PPC, Web design and development, WooCommerce. We know how to help small businesses because we are one.'
  menu:
    main:
      - name: 'SEO'
        url: '/'
        weight: 10
      - name: 'Services'
        url: '/seo/'
#        identifier: services
        weight: 20
#      - name: 'Search Engine Optimization'
#        parent: services
#        weight: 10
      - name: Success Stories
        url: '/success-stories/'
        weight: 30
      - name: 'About us'
        url: '/#about'
        weight: 40
      - name: 'Get a Quote'
        url: '/#contact'
        weight: 50